name: COMMENT

on:
  issue_comment:
    types: [created]

jobs:
  push-comment:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'pick')
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo "${{ toJson(github.event) }}"
#      - name: Send dingding notify
#        uses: zcong1993/actions-ding@master
#        with:
#          dingToken: ${{ secrets.PICKER_DINGTALK_KEY }}
#          secret: ${{ secrets.PICKER_DINGTALK_SECRET }} # if secret set, action will call API with sign
#          body: |
#            {
#              "msgtype": "markdown",
#              "markdown": {
#                  "text": "这个即将发布的新版本，创始人陈航（花名“无招”）称它为“红树林”。而在此之前，每当面临重大升级，产品经理们都会取一个应景的代号，这一次，为什么是“红树林”？",
#                  "title": "${{ github.event.issue }}",
#                  "picUrl": "",
#                  "messageUrl": "https://www.dingtalk.com/s?__biz=MzA4NjMwMTA2Ng==&mid=2650316842&idx=1&sn=60da3ea2b29f1dcc43a7c8e4a7c97a16&scene=2&srcid=09189AnRJEdIiWVaKltFzNTw&from=timeline&isappinstalled=0&key=&ascene=2&uin=&devicetype=android-23&version=26031933&nettype=WIFI"
#              }
#            }