name: COMMENT

on:
  issue_comment:
    types: [created]

jobs:
  push-comment:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'pick')
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo '${{ toJson(github.event.comment.body) }}'
#      - name: Send dingding notify
#        uses: zcong1993/actions-ding@master
#        with:
#          dingToken: ${{ secrets.PICKER_DINGTALK_KEY }}
#          secret: ${{ secrets.PICKER_DINGTALK_SECRET }}
#          body: |
#            {
#              "msgtype": "markdown",
#              "markdown": {
#                  "text": " ${{ github.event.issue.user.login }} 评论了 [${{ github.event.issue.title }}](${{ github.event.comment.html_url }}): \n\n${{ github.event.comment.body }}",
#                  "title": "${{ github.event.issue.title }} 新增评论"
#              }
#            }
