name: ISSUE

on:
  issues:
    types: [opened]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    if: github.event.issue.labels == fromJson('[]')
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: pick
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.issue.labels.*.name }}